name: Deploy to AWS S3 & EC2 via SSM

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 👈 Allows running manually in GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload Code to S3
        run: |
          aws s3 sync . s3://satellite-deploy-bucket-1741650405/Satellite-Interactive-Visualizer-And-Fleet-Optimization/ --delete

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets Key=instanceIds,Values=i-00c9fcbd5c444d78a \
            --parameters 'commands=["aws s3 sync s3://satellite-deploy-bucket-1741650405/Satellite-Interactive-Visualizer-And-Fleet-Optimization/ ~/Satellite-Interactive-Visualizer-And-Fleet-Optimization/ --delete", "bash ~/Satellite-Interactive-Visualizer-And-Fleet-Optimization/deploy.sh"]' \
            --region us-east-2
