name: Update Satellite Data (GitHub Actions + Docker)

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_satellites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Updater in Docker
        run: |
          docker build -t satellite-updater -f backend/Dockerfile.update ./backend
          docker run --rm \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_PORT=5432 \
            -e SPACETRACK_USER=${{ secrets.SPACETRACK_USER }} \
            -e SPACETRACK_PASS=${{ secrets.SPACETRACK_PASS }} \
            satellite-updater
