name: Update Satellites & Infographics

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 06:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Env Vars
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "SPACETRACK_USER=${{ secrets.SPACETRACK_USER }}" >> $GITHUB_ENV
          echo "SPACETRACK_PASS=${{ secrets.SPACETRACK_PASS }}" >> $GITHUB_ENV

      - name: Build & Run Updater
        run: |
          docker build -t satellite-updater -f backend/Dockerfile.update ./backend
          docker run --rm \
            -e DB_HOST=$DB_HOST \
            -e DB_NAME=$DB_NAME \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e SPACETRACK_USER=$SPACETRACK_USER \
            -e SPACETRACK_PASS=$SPACETRACK_PASS \
            satellite-updater

  generate_infographics:
    runs-on: ubuntu-latest
    needs: update_db

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: |
          pip install -r backend/requirements.txt
          # If these aren't in your requirements
          pip install matplotlib seaborn pandas

      - name: Make Infographics Dir
        run: |
          mkdir -p backend/infographics

      - name: Generate Infographics
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: 5432
        run: |
          # 1) Import filters and generate_infographics from the file
          # 2) Loop over the filters
          # 3) Generate "Launch Year" and "Country" too
          python -c "
          import os
          os.environ['DB_HOST'] = '${DB_HOST}'
          os.environ['DB_NAME'] = '${DB_NAME}'
          os.environ['DB_USER'] = '${DB_USER}'
          os.environ['DB_PASSWORD'] = '${DB_PASSWORD}'
          os.environ['DB_PORT'] = '${DB_PORT}'

          from backend.app.generate_infographics import filters, generate_infographics

          print('🔄 Generating Infographics for all filters...')
          for f_name, f_condition in filters.items():
          generate_infographics(f_name, f_condition)

          print('🔄 Generating Infographics for Launch Year (All)...')
          generate_infographics('Launch Year (All)', None)

          print('🔄 Generating Infographics for Country (All)...')
          generate_infographics('Country (All)', None)
              "
      - name: Commit & Push Updated Graphs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/infographics/*.png
          git commit -m "📊 Auto-update satellite infographics (Daily)" || echo "No changes to commit"
          git push
